import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import style from "@/styles/Home.module.css";
import { AiOutlineSearch } from "react-icons/ai";
import Navbar from "@/component/Navbar";
import Why from "@/component/Why";
export default function Home() {
  const [buy, setBuy] = useState(true);
  const [sell, setSelling] = useState(false);
  const [rent, setRent] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={style.bg}>
        <div className={style.headline}>
          <h2>
            Let Us Help You
            <br />
            To Choose <br />
            The Best
          </h2>
          <p>
            Become what you live, live in what you want to become,
            <br /> Life is too short to hold back push on with renters Become
            <br />
            what you live, live in what you want to become, Life is too
          </p>
          <div className={style.btn}>
            <button>Learn More</button>
            <div className={style.video}>
              <div className={style.watch}>
                <img src="/vid.png" priority />
                <img src="/Vector.png" priority className={style.vector} />
              </div>
              <p>Watch Video</p>
            </div>
          </div>
        </div>

        <div className={style.bg1}>
          <img src="/house.svg" priority className={style.img1} />
          <img src="/house3.svg" className={style.img2} />
          <img src="/house2.svg" className={style.img3} />
          <img src="/shadow.svg" className={style.img4} />
        </div>
      </div>
      <Why />
    </>
  );
}
